### ISSUE TITLE
bot failing some missions

### ISSUE THREAD

**Issue by rizar** [mila-udem/babyai#11]
The bot fails the mission #1308. I investigated, and here is what happens. Let's look at  https://github.com/mila-udem/babyai/blob/9ed5e0db5692f6229dbe339d2d597e863d4dd9de/babyai/bot.py#L1210

What seems to happen here is that after the agent picks up an object, it may have to drop it before it reaches the location where the object must be dropped. For example, if the instruction is "put a ball next to the red door", and if the ball needs to be dropped on the way to the red door in order to unblock the path, the bot gets lost. Is my reasoning correct? 

To fix this issue one would need to change the behavior of `GoTo...` subgoals in a way that the agent does not lose what it's carrying. Would that be a reasonable solution?

**Comment by maximecb** [comment]
Is this on BossLevel?

I'm surprised we're getting all these new failures. For sure this kind of thing was handled correctly before the changes to the bot. The bot is supposed to pick back up what it was carrying if it has to unblock something (@saleml ?).

**Comment by rizar** [comment]
We discussed this with @saleml , he said he can fix it
