### ISSUE TITLE
support Python reference as an argument in GoNextTo

### ISSUE THREAD

**Issue by rizar** [mila-udem/babyai#28]
... in order to stop changing the stack in `DropSubgoal`.

That's a little but important refactoring that can prevent bad bugs in the future.

**Comment by maximecb** [comment]
FYI, in dynamic/managed languages, the term is not pointer, but reference.

**Comment by rizar** [comment]
Can't argue with an expert!

For me, Pascal/C++ were my first languages, and learning Java/Python started with repeating to myself the "everything is a pointer" mantra.
