### ISSUE TITLE
go straight for the key when you head for locked door

### ISSUE THREAD

**Issue by rizar** [mila-udem/babyai#29]
Out of the suboptimal things that the bot does, this one stands out --- why go to the locked door without the key if you know it's locked?? Should be not too hard to fix, but will require full-scale testing (as usual).

**Comment by maximecb** [comment]
We'll should choose whether we do this or not before regenerating all the demos IMO. Once the demos are regenerated and the updated paper is out, it would be best to avoid changing the bot if possible.

**Comment by rizar** [comment]
Yes, I agree that it is time to finalize the ICLR version of the bot. I've tried to quickly make this change to the bot, and I found it not super-easy. Doing this properly requires copying a lot of code from `OpenSubgoal` to `GoNextToSubgoal`, the code that is responsible for dropping the key after the door is open and for picking up the object that the agent was carrying when it decided to go for the key. I can imagine another refactoring that makes this behavior more natural to implement, but I am not sure if this suboptimality is so important... what do you think?

**Comment by maximecb** [comment]
If you can get it working by Jan 31st it could be ok. By then we really need to generate the demos and make sure that the code to run the experiments is still working correctly. Might be wise to start some test runs without waiting for all the demos to be generated.
