### ISSUE TITLE
Make train_intelligent_expert.py resumable

### ISSUE THREAD

**Issue by maximecb** [mila-udem/babyai#37]
Working on this issue today. I will make the script save the generated demos, and also start from the set of loaded demos instead of always generating them.

**Comment by maximecb** [comment]
@rizar I have a WIP that saves the demos and the seed used to generate demos. With the caveat that if training is interrupted, it will restart the training for that phase when resumed. Is that ok, or do we expect interruptions to be frequent enough for that to be a problem?

Another issue is that I'm kind of breaking the dagger code. Though I'm not sure we ever actually implemented dagger properly, so I would propose removing those bits if you don't mind.

**Comment by maximecb** [comment]
Actually, I think I've succeeded in making it reload the model, hurray.

Are you ok with me removing the dagger code?

**Comment by rizar** [comment]
Yes, I'm fine with removing DAGGER for now, we can add it back once we have
a version that for sure works.
